site_name: USU OPTT Web Forms

theme:
  name: material
  features:
    - navigation.instant
  palette:
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode

repo_url: https://github.com/jarenglenn/usu-optt-forms/
repo_name: jarenglenn/usu-optt-forms

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Tools: tools.md
  - Rubrics: rubrics.md
  - State Management: stateManagement.md
  - General Notes: notes.md
