site_name: USU OPTT Web Forms

theme:
  name: material
  features:
    - navigation.instant

repo_url: https://github.com/jarenglenn/usu-optt-forms/
repo_name: jarenglenn/usu-optt-forms

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Home: index.md
  - Tools: tools.md
  - Rubrics: rubrics.md
  - State Management: stateManagement.md
  - General Notes: notes.md
